### ISSUE TITLE
Plugin description is wrong

### ISSUE THREAD

**Issue by gundestrup** [litespeedtech/lscache-joomla#1]
It states
"LiteSpeedCache is a hign performance cache solution for MediaWiki sites running on LiteSpeed Web Server."

It should proberly be "joomla"

**Comment by jacksonlst** [comment]
Thanks for the report. I just checked and seem correct/or changed already.  

Thank you again.

**Comment by gundestrup** [comment]
I just tree hours ago downloaded the plugin....?

**Comment by gundestrup** [comment]
It's not fixet
https://github.com/litespeedtech/lscache-joomla/blob/master/lscache_plugin/lscache.xml

<description>LiteSpeedCache is a hign performance cache solution for MediaWiki sites running on LiteSpeed Web Server.</description>

**Comment by WuhuaChen** [comment]
Fixed now, Thanks for report.
