### ISSUE TITLE
Home Page Cache Issue

### ISSUE THREAD

**Issue by Ahmedfouad2** [litespeedtech/lscache-joomla#16]
First I wish to thank all the team members that worked hard to bring us this Joomla Extension.
It seems that Home page cache does not respect modules (render as ESI) rules and cache every thing aggressively or I miss configure it.

**Comment by WuhuaChen** [comment]
If a module is set to Render as ESI, by default this ESI module is also cache publicly.  If you want this ESI module not be cached, you need to config it via "Component->LiteSpeedCache", in search bar, select "ESI Modules", find that ESI module ,  click the title link,  then set "ESI Module Cache Type" to "None".
But it will affect performance, so normally we do not recommend use "None" cache ESI module.  only some login module may not support cache, it need to set as "None" cache.

**Comment by Ahmedfouad2** [comment]
Thank you very much :)

**Comment by gundestrup** [comment]
Is this tested and working?
