### ISSUE TITLE
Error when Rebuilding the Update Datbase

### ISSUE THREAD

**Issue by jimhill10** [litespeedtech/lscache-joomla#18]
Litespeed produces an error when you rebuild the extension update database. To reproduce, log into the back end, Extensions, Update Sites. Select Rebuild.  Then an error results:
`Call to undefined method plgSystemLSCache::getTemplate()`

Screen shot [here](https://i.imgur.com/nlDINxA.png)

**Comment by gundestrup** [comment]
Should it not be closed? I have not see the error since updating?
