### ISSUE TITLE
Error while purging cache

### ISSUE THREAD

**Issue by shayandavoodi** [litespeedtech/lscache-joomla#21]
Hey there.

I have added
`<IfModule LiteSpeed>
CacheLookup on
</IfModule>`
to my .htaccess file and the **component** is installed.
When I press "Purge all litespeed cache" button, I get this error:
`An error has occurred.
500 Library path /plugins/system/lscache/lscachebase.php cannot be found.`

I tested on 2 different servers and I got the same issue on both.

Please note that there is no plugin installed when I install the component.

**Comment by WuhuaChen** [comment]
Thanks for reporting,  we found a bug will cause that error when LiteSpeed Cache plugin was disabled. we fixed it in 1.2.0 version, please download and install the 1.2.0 version package in github "package" directory.  Thanks.

**Comment by shayandavoodi** [comment]
When I install the component, there is no plugin installed with it.
It just installs a component not any plugin.

**Comment by WuhuaChen** [comment]
The cache plugin is packaged together with the component.  in Joomla admin back end, in menu Extensions->Plugins , you can search LiteSpeed ,  will find LiteSpeed Cache Plugin .

**Comment by shayandavoodi** [comment]
I got it sir, Thank you.

This is the response header that I get:

`
X-LiteSpeed-Cache-Control: public,max-age=60
X-LiteSpeed-Tag: 8c70,8c70com_menus:588,8c70com_menus,8c70com_content:89,8c70template:sitestory-v3/com_content/category/blog
`
There is no
`X-LiteSpeed-Cache: HIT`

Is that correct?

**Comment by WuhuaChen** [comment]
Normally when you open a web page at first time,  the response header is like that.  then you can refresh that web page again,  the second time it will show "X-LiteSpeed-Cache: HIT".  
But it looks like you set a too short  "public cache TTL' to 1 minute, That means the cache will expire in 60 seconds,  after that if you open that web page again, the response header will like you visit it at the first time.

**Comment by jimhill10** [comment]
Make sure that you installed correctly:
-Add the required rule to htaccess
### LITESPEED_CACHE_START - Do not remove this line
<IfModule LiteSpeed>
CacheLookup on
</IfModule>
### LITESPEED_CACHE_END

-Install the Joomla package, then activate the Litespeed system plugin. 
[https://github.com/litespeedtech/lscache-joomla/archive/master.zip](https://github.com/litespeedtech/lscache-joomla/archive/master.zip) 

-Check the Litespeed component settings and make sure that page you are viewing is not excluded. Refresh that page twice. Look for cache hit.

**Comment by shayandavoodi** [comment]
@jimhill10 

- The code exists in .htaccess file. Even its comments exist.
- Component doesn't have anything excluded from being cached.

Does this response header have any issue?

**Comment by shayandavoodi** [comment]
@WuhuaChen Thanks for your time.
I am still getting the same response header even on future visits.

This is all I have in my .htaccess file about caching. This is a fresh Joomla! installation.
`### LITESPEED_CACHE_START - Do not remove this line
<IfModule LiteSpeed>
CacheLookup on
</IfModule>
### LITESPEED_CACHE_END`
This is all I have in my .htaccess file about caching. This is a fresh Joomla! installation.
I am on a shared hosting. I don't have access to the control panel of Litespeed web server.
How can I check if cache storage is set properly?
Is there any way like seeing it in phpinfo or sth?

When I put this directive in .htaccess file,
`########## Begin - Litespeed cache
<IfModule LiteSpeed>
  RewriteEngine On
  CacheDisable public /
  RewriteCond %{REQUEST_METHOD} ^HEAD|GET$
  RewriteCond %{ORG_REQ_URI} !/administrator
  RewriteRule .* - [E=Cache-Control:max-age=120]
</IfModule>
########## End - Litespeed cache`
There is no response header related to litespeed cache.

I contacted my hosting provider, I will update this thread soon.

**Comment by shayandavoodi** [comment]
@jimhill10 Can you confirm that this response header on every visit indicates some problem?

`X-LiteSpeed-Cache-Control: public,max-age=60 X-LiteSpeed-Tag: 8c70,8c70com_menus:588,8c70com_menus,8c70com_content:89,8c70template:sitestory-v3/com_content/category/blog`

**Comment by jimhill10** [comment]
This a portion of the header on a typical page I have set to be cached:
hitserver	 LiteSpeed status	 200 strict-transport-security	 max-age=31536000 vary	 Accept-Encoding x-litespeed-cache	

Your htacess directive is the old code which was formerly required.  You need to use the new code thye provided in the documentation when you use the Litespeed package (component and plugin):

`### LITESPEED_CACHE_START - Do not remove this line
<IfModule LiteSpeed>
CacheLookup on
</IfModule>
### LITESPEED_CACHE_END
`
