### ISSUE TITLE
Notice: Undefined offset: 1 in /plugins/system/lscache/lscache.php on line 730

### ISSUE THREAD

**Issue by jimhill10** [litespeedtech/lscache-joomla#22]
I am seeing this warning (not error) in the back end on Joomla 3.8.8:
Notice: Undefined offset: 1 in /plugins/system/lscache/lscache.php on line 730

**Comment by WuhuaChen** [comment]
Which version of LiteSpeed Cache plugin are you using,  I can't locate this problem in current version code.

**Comment by jimhill10** [comment]
We are on 1.2.0. That warning shows with debug enabled and error reporting on maximum.  Shows on my dev site.  If nobody else sees it then I suggest just closing it and waiting to see if others report it.

**Comment by ssnobben** [comment]
I also get this notification error having Joomla set to report "Maximum"  Notice: Undefined offset: 1 /plugins/system/lscache/lscache.php on line 797  Joomla 3.9.11 and latest LMS cache version

**Comment by uglyeoin** [comment]
Me too.  Only in the admin.

**Comment by ssnobben** [comment]
Same here in the admin of Joomla 3.9.14

**Comment by uglyeoin** [comment]
@ssnobben I approached in the Slack group and got a code fix :)  Maybe try that?  I'm sure he wouldn't mind if I shared the code.

**Comment by ssnobben** [comment]
ok thats would be nice. where can I find the code?

**Comment by uglyeoin** [comment]
[lscache-latest.zip](https://github.com/litespeedtech/lscache-joomla/files/3995262/lscache-latest.zip)

**Comment by uglyeoin** [comment]
I'm sure he won't mind and I'm probably saving him a job in reality :)

**Comment by uglyeoin** [comment]
Maybe @jimhill10 can close this issue now and help him too?

**Comment by ssnobben** [comment]
Q: So is this the same or newer than https://github.com/litespeedtech/lscache-joomla and/or with update from  @WuhuaChen 12 days ago?

**Comment by uglyeoin** [comment]
@ssnobben I'm afraid I couldn't tell you the answer to that.  But I received it on 11/12/2019 so probably the same or older.  I'd use the Github version if I were you.  Does the latest version solve your problem?  And if not.... does this version?  

Recommended action.  
1. Backup, backup, backup.
2. Install the latest github version
3. Test if it's fixed.  If it is then... 
4.  If it isn't install my version and test if it's fixed.
5.  If it is then you should compare both files using some sort of a diff program and then merge the differences if you can which would hopefully bring you the result you want.

Then you should raise a pull request here to help out the author with his great work.  I suspect it is the right version though.  Let me know.  It's Christmas I'll try to help.   But also... I had success in the Slack channel so perhaps joining that is a better way to raise support requests from now on :)

**Comment by jimhill10** [comment]
I am no longer seeing this issue using the latest versions of Joomla and Lscache.  I can close this. Testing it again just now.
