### ISSUE TITLE
Pagination problem

### ISSUE THREAD

**Issue by Ahmedfouad2** [litespeedtech/lscache-joomla#26]
Litespeed Joomla extension + Virtuemart
Some times pages like
SECTION(1)/Products page (1)
and 
SECTION(1)/products page (2)
both indexed as the same page

link/section(1)/products page (2) URL display link/section(1)/products page (1)

**Comment by Ahmedfouad2** [comment]
I installed the latest update the problem still present some cache files isn't cleaned even if I pressed (puerge all litespeed cache files )

**Comment by wuhua68** [comment]
Thanks for report, sorry I didn't notice this ticket on time.  You can join [our slack community](https://bit.ly/2NDrSXM )  and  "joomla-cache" channel , we can give you live support.
If  Products page (1) and Products page (2)  is same url, it should be indexed as the same page.  but in my virtuemart site and some other site different pages are different url.  so I need more information to locate the problem.

**Comment by Ahmedfouad2** [comment]
Hello there,
It's OK
Some times both of this URL
https://tajr.shop/ar/shop/gemstones
https://tajr.shop/ar/shop/gemstones?start=12
displays the same content
I willing to give any informations required privately.
