### ISSUE TITLE
First time load of a divice gives always an Error 500

### ISSUE THREAD

**Issue by gundestrup** [litespeedtech/lscache-joomla#3]
Setting
I cleared cache.
I then accessed the website from a desktop computer, error 500
I then reloaded, then the page loaded correctly.

I then accessed the website from a cell phone (android), error 500
I then reloaded, the page loaded correctly (minor errors) - some images missing button of page (see seperate issue)

**Comment by jacksonlst** [comment]
Can you log a ticket with us with tmp root ssh access to take a look?

**Comment by gundestrup** [comment]
I have a ticket at your site "261488".
They suggested that I tried the plugin at github.
Contect me, through that ticket, and get root access to server, and super admin access to the a2.lungekursus.dk website...

**Comment by gundestrup** [comment]
I will sende login info soon

**Comment by jacksonlst** [comment]
It has been fixed by disabling JotCache and Joomla system page cache plugin.  Should not use two-page cache solution at the same time.   To disable both before enabling LiteSpeed cache plugin

**Comment by gundestrup** [comment]
The problem was not jotcache, but an lack of mem to php.
After this was increased, it works.
IT was NOT related to lscache-joomla
