### ISSUE TITLE
New PHP Warnings

### ISSUE THREAD

**Issue by jimhill10** [litespeedtech/lscache-joomla#30]
These PHP warnings are now showing in the logs after the latest version, they were not present before.

`PHP Warning:  Creating default object from empty value in /home/username/public_html/plugins/system/lscache/lscache.php on line 560
PHP Warning:  Creating default object from empty value in /home/username/public_html/plugins/system/lscache/lscache.php on line 566
PHP Notice:  Undefined offset: 1 in /home/username/public_html/plugins/system/lscache/lscache.php on line 730`

These are present on both my dev and production environments on Joomla 3.9.0.

**Comment by wuhua68** [comment]
Thanks for report.
 I just released a new version for Joomla 3.9.0 ,  you can download it from [GitHub package folder](https://github.com/litespeedtech/lscache-joomla/blob/master/package/lscache-1.3.0.zip) . If still show this kind of warning please let me know. thanks.

**Comment by wuhua68** [comment]
It just purge the page cache of the given URL.
