### ISSUE TITLE
Rsform form doesn't work with lscache / esi module and exclude fail

### ISSUE THREAD

**Issue by stresskills** [litespeedtech/lscache-joomla#31]
PHP 7.2.4
Joomla 3.8.11
RSForm! Pro 2.0.13
lscache 1.3.0

Default Joomla Cache:
everything works

Lscache no esi module:
1st form submission- loads form, and submits correctly (database and email)
2++ form submissions- loads form, and looks like it submits but nothing in database or email

Lscache YES esi module / cache type=none:
1st form submission- loads form, and looks like it submits but nothing in database or email
2++ form submissions- same

If I clear cache it will cache the "Thank you" message until cache is cleared.
I would really appreciate any advice on where to start.

Where is debug logged to?

**Comment by jimhill10** [comment]
Here is how I have my system set up.  No Redis, not memcached, no file caching as this is done through LS.
1.  In global configuration, set caching to OFF.
2. I'm using SH404SEF.  I have installed the shlib system plugin and enabled memcached in that plugin so it makes the routing function faster.  This is the shared memory engine for PHP. Otherwise, all system caches are off. 
3. System page cache plugin off. 
4. Lscache plugin ordered last but just before JCH Optimize. 
5. As you say, for every module type "Rsform" set to ESI in Ls Cache component.
6. In Ls cache component provide an exclusion for the phrase "nocache."
7. For all thank you pages connected to Rsforms, code the URL with suffix ?nocache as a preventative measure to be certain nothing is cached.

**Comment by stresskills** [comment]
@jimhill10 Sorry for my ignorance but I have a few questions. Thank you for your help!

I'm using SH404SEF. I have installed the shlib system plugin and enabled memcached in that plugin so it makes the routing function faster. This is the shared memory engine for PHP. Otherwise, all system caches are off.
// Does that mean that lscache is not caching URLs?

Lscache plugin ordered last but just before JCH Optimize.
// Will that prevent caching of js / css? Just curious why as I do use JCH Optimize.

**Comment by jimhill10** [comment]
-The URL cache in SH404SEF has to do with how it caches requests for the SEO friendly URL, not whether or not LScache caches that page.  
-You are correct. I was using the function in SH404SEF to set the automatic plugin order.  If you are using a CDN the combined files (js / CSS) will come from the CDN anyway. 
With JCH Optimize I had to be careful with Akeeba Admin Tools using their htacess builder as the path to the files had to be allowed.
Also, I am working with a dev server on Cloudways (Digital Ocean, 1 CPU, 2 GB) using Redis to see what performance gains I can make.  We also use SP Builder and there is just a bit of overhead from that.

**Comment by stresskills** [comment]
Thank you for the explanation. I started working with your notes but this is a live site so I'm testing on off hours.
PS: I have same setup JCH w/ CDN, SH404SEF, admintools, usually built on Helix Ultimate w/ SP Page builder if you ever want to compare notes..

**Regardless of the work around looks like ESI Doesn't work as expected. I have updated to current version of litespeed and still not working.**

**Comment by jimhill10** [comment]
On my site in Joomla 3.9.1 the ESI is broken, makes errors with the T3 framework plugin.  Any page which loads a module set to ESI makes the error.  I had reported this earlier in another thread but thought I had corrected it.  Will post this again.  I came to Litespeed initially with great success from NGINX / Apache reverse proxy / Varnish.  This is getting old having it break after every upgrade.

**Comment by WuhuaChen** [comment]
@stresskills , Thanks for reporting, we already tested that T3 framework plugin ESI problem can be fixed, please see [this link](https://github.com/litespeedtech/lscache-joomla/issues/32) for detail information.
If your RSFORM problem still can not be fixed, please give me a installation package file of your current RSForm and SH404SEF version, I'll try to reproduce and fix this issue. you can send it to wchen@litespeedtech.com .

**Comment by jimhill10** [comment]
I would love to compare notes @stresskills sometime.  My gmail is jimhill10.  Let's connect.
