### ISSUE TITLE
Broken due to Conflict with T3 System Plugin on Joomla 3.9.1

### ISSUE THREAD

**Issue by jimhill10** [litespeedtech/lscache-joomla#32]
Had to disable the LS cache plugin after upgrading from Joomla 3.9.0 to 3.9.1 due to error: 
"Class 't3 path' not found."  Here is a stack trace. 

`A PHP Exception occurred on your site. Here you can find the stack trace:
Exception Type: Error
File: /home/accountname/public_html/plugins/system/t3/t3.php
Line: 355
Message: Class 'T3Path' not found 
#0 /home/accountname/public_html/libraries/joomla/event/event.php(70): plgSystemT3->onRenderModule(Object(stdClass), Array)
#1 /home/accountname/public_html/libraries/joomla/event/dispatcher.php(160): JEvent->update(Array)
#2 /home/accountname/public_html/libraries/src/Application/BaseApplication.php(108): JEventDispatcher->trigger('onrendermodule', Array)
#3 /home/accountname/public_html/libraries/src/Helper/ModuleHelper.php(245): Joomla\CMS\Application\BaseApplication->triggerEvent('onRenderModule', Array)
#4 /home/accountname/public_html/plugins/system/lscache/lscache.php(1345): Joomla\CMS\Helper\ModuleHelper::renderModule(Object(stdClass), Array)
#5 /home/accountname/public_html/libraries/joomla/event/event.php(70): plgSystemLSCache->onAfterInitialise()
#6 /home/accountname/public_html/libraries/joomla/event/dispatcher.php(160): JEvent->update(Array)
#7 /home/accountname/public_html/libraries/src/Application/BaseApplication.php(108): JEventDispatcher->trigger('onafterinitiali...', Array)
#8 /home/accountname/public_html/libraries/src/Application/CMSApplication.php(626): Joomla\CMS\Application\BaseApplication->triggerEvent('onAfterInitiali...')
#9 /home/accountname/public_html/libraries/src/Application/SiteApplication.php(686): Joomla\CMS\Application\CMSApplication->initialiseApp(Array)
#10 /home/accountname/public_html/libraries/src/Application/SiteApplication.php(212): Joomla\CMS\Application\SiteApplication->initialiseApp()
#11 /home/accountname/public_html/libraries/src/Application/CMSApplication.php(196): Joomla\CMS\Application\SiteApplication->doExecute()
#12 /home/accountname/public_html/index.php(49): Joomla\CMS\Application\CMSApplication->execute()
#13 {main}
Request information
GET variables
Array
(
    [option] => com_lscache
    [view] => esi
    [moduleid] => 560
    [device] => desktop
    [language] => en-US
    [attribs] => name,footer-2;style,T3Xhtml
)
POST variables
Array
(
)
COOKIE variables
Array
(
)
REQUEST variables
Array
(
    [option] => com_lscache
    [view] => esi
    [moduleid] => 560
    [device] => desktop
    [language] => en-US
    [attribs] => name,footer-2;style,T3Xhtml
)
SERVER variables
Array
(
    [PATH] => /bin:/usr/bin:/usr/local/bin
    [HTTP_ACCEPT] => */*
    [HTTP_ACCEPT_ENCODING] => identity, deflate, *;q=0
    [HTTP_HOST] => www.ufcinc.com
    [HTTP_USER_AGENT] => Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/70.0.3538.102 Safari/537.36
    [DOCUMENT_ROOT] => /home/accountname/public_html
    [REMOTE_PORT] => 33608
    [SERVER_NAME] => www.ufcinc.com
    [SERVER_ADMIN] => email@domain.com
    [SERVER_PORT] => 443
    [REQUEST_URI] => /index.php?option=com_lscache&view=esi&moduleid=560&device=desktop&language=en-US&attribs=name,footer-2;style,T3Xhtml
    [HTTPS] => on
    [ESI_REFERER] => /?jchbackend=2
    [SSL_PROTOCOL] => TLSv1.2
    [SSL_SESSION_ID] => e0d8b2938065e33a72e0083abf0b05f831e12c73a980616e2ce0544ae16276d9
    [SSL_CIPHER] => ECDHE-RSA-AES128-GCM-SHA256
    [SSL_CIPHER_USEKEYSIZE] => 128
    [SSL_CIPHER_ALGKEYSIZE] => 128
    [SCRIPT_FILENAME] => /home/accountname/public_html/index.php
    [QUERY_STRING] => option=com_lscache&view=esi&moduleid=560&device=desktop&language=en-US&attribs=name,footer-2;style,T3Xhtml
    [SCRIPT_URI] => https://www.ufcinc.com/index.php
    [SCRIPT_URL] => /index.php
    [SCRIPT_NAME] => /index.php
    [SERVER_PROTOCOL] => HTTP/1.1
    [SERVER_SOFTWARE] => LiteSpeed
    [REQUEST_METHOD] => GET
    [X-LSCACHE] => on
    [PHP_SELF] => /index.php
    [REQUEST_TIME_FLOAT] => 1543339825.383
    [REQUEST_TIME] => 1543339825
)
`

**Comment by jimhill10** [comment]
I tracked this down to some coding I had in a custom html module. The coding was correct but it used an exclusion slug (?nocache) in the URL.  I re-coded this to use a menu item instead and the issue went away.

**Comment by wuhua68** [comment]
@jimhill10  I just tested in Joomla 3.9.1 and T3 framework (theme + plugin), I found that if LiteSpeed Cache plugin priority is before T3 plugin, no problem,  if LiteSpeed Cache plugin priority is after T3 plugin, this problem occurs.  You can set LiteSpeed Cache plugin priority in Joomla admin panel : Extension->plugins .

**Comment by jimhill10** [comment]
Thanks, I am trying that order to see what happens.

**Comment by jimhill10** [comment]
That took away my error.  I have the last three plugins as T3, Lscache, and JCH Optimize (last).
