### ISSUE TITLE
Images have the wrong URL

### ISSUE THREAD

**Issue by uglyeoin** [litespeedtech/lscache-joomla#33]
Images have the wrong URL, they are relative to the page, not the base of the site.

So for example instead of being /images/myLogo.jpg they are being returned as

mywebsite.com/apage/images/myLogo.jpg which is causing them to be 404s.

**Comment by WuhuaChen** [comment]
Is it an ESI module? lscache plugin will not change page content, only ESI module may affect the content.

**Comment by uglyeoin** [comment]
It is not an ESI module.  You can say it will not change content, but disabling the plugin solves the problem, so I think there is something in the plugin that is doing this.

**Comment by WuhuaChen** [comment]
if the myLogo.jpg  is  inside the login module, it should be a ESI problem. because login module was rendered as ESI by default.

**Comment by uglyeoin** [comment]
But I have just turned the extension on, I have not set any modules to be ESI modules

**Comment by WuhuaChen** [comment]
You can try in LiteSpeed Cache Options panel -> advanced -> Render Login Module as ESI  -> disabled , then purge all cache to see if still have this problem.   I guess it's caused by ESI, if it's not, please send detail information of your site to wchen@litespeedtech.com , I'll check it with you. Thanks.

**Comment by uglyeoin** [comment]
Crap.  Just realised this site is on a totally different server!  Consider this closed for now, but I believe I have been this error before.  I'll reopen it if I find it again.  Sorry for wasting your time.
