### ISSUE TITLE
Missing images on website, when using LSCache

### ISSUE THREAD

**Issue by gundestrup** [litespeedtech/lscache-joomla#4]
Setting:
A2Hosting, managed hosting enviroment.
CMS: Joomla 3.8.5
Plugins: JCH optimizer, Jotcache (memcached, device specific)
Caching setting: memcached, device specific

Problem: Some images does not load correctly on buttom of website
link: a2.lungekursus.dk
There should be the following images: AstraZenica, Teva,Roche, Alk,Novartis, Boehring Ingelheim.
Ord link www.lungekursus.dk

This is only a problem on the mobile device.

The original website www.lungekursus.dk, loads correctly (An Apache 2.4 webserver, memcached ....) Same website, just not LiteSpeed cache or webserver.

I tested JCH Optimizer, now as Lasyload + Force Load -> That seems to work.
But still a change since Apache.

**Comment by jacksonlst** [comment]
www.lungekursus.dk homepage looks ok to me when I use Desktop Chrome and Iphone Safari to access it.  Both works fine from my point of view. Can you give us an example URL with the problem and steps to reproduce it?

**Comment by gundestrup** [comment]
My original site is www.lungekursus.dk (running on apache)- hosted at digital ocean (my own server)
The site with a problem is a2.lungekursus.dk (hosted at a2hosting, a vps managed server, I am migrating to (if I can get proper speeds), litespeed server + litespeed cache)

I has to disable lasy loading of images on the litespeed server (a2.lungekursus.dk), the website load correctly. (that is a change form my apache server)

**Comment by jacksonlst** [comment]
What do you means "lasy loading of images" and where to set it?  LiteSpeed cache plugin for Joomla doesn't have such function for it.  Not sure how you turn it off/on.

By the way,  you will need to turn off other full page cache plugin ( such as Jotcache)  before enabling litespeed cache plugin for Joomla

**Comment by jacksonlst** [comment]
Doesn't seem to to happen when we got login and checked.

**Comment by gundestrup** [comment]
After release it and the updates, it looks like it's working
