### ISSUE TITLE
Cache plugin conflict with RegularLabs Advanced Module Manager

### ISSUE THREAD

**Issue by Scrabble96** [litespeedtech/lscache-joomla#41]
I have just installed the LiteSpeed Cache plugin (v1.3.2 downloaded today) on my Joomla 3.9.24 website. I'm on a shared LiteSpeed server, but the owners have confirmed that LS Cache for Joomla is installed and enabled on the server.

I also have RegularLabs Advanced Module Manager (v7.14.1) and Cache Cleaner (v7.3.3) installed on the website.

When both Regular Labs' and your cache cleaner plugins are enabled and I publish or unpublish a module the status of the module on the front end does not change. I have to disable the LS Cache first.

**Comment by ch2856** [comment]
You need to clear cache on such a change.
