### ISSUE TITLE
Use of undefined constant current

### ISSUE THREAD

**Issue by M-Falken** [litespeedtech/lscache-joomla#45]
Hi,
on the last version 1.5.0
I'm with PHP 7.4.21
PHP Warning:  Use of undefined constant current - assumed 'current' (this will throw an Error in a future version of PHP) in ./plugins/system/lscache/components/com_virtuemart.php on line 289 (293 with actual file)

https://github.com/litespeedtech/lscache-joomla/blob/712a2f9acb1eee0f8efa1152268b316b3a784e8e/lscache_plugin/components/com_virtuemart.php#L293

Thanks

**Comment by M-Falken** [comment]
Nobody ?

**Comment by WuhuaChen** [comment]
hi, fixed this issue in https://github.com/litespeedtech/lscache-joomla/commit/8d67db43de00c550386dc9ecb2b16371b59349b1 .
also submitted relate package:
joomla3:  https://github.com/litespeedtech/lscache-joomla/blob/master/Joomla3/package/lscache-latest.zip
joomla4:  https://github.com/litespeedtech/lscache-joomla/blob/master/Joomla4/package/lscache-latest.zip

**Comment by M-Falken** [comment]
Thanks a lot
