### ISSUE TITLE
Notice: Trying to get property 'id' of non-object in lscache.php on line 209

### ISSUE THREAD

**Issue by RedDustSnow** [litespeedtech/lscache-joomla#49]
Hi, just installed lscache on Joomla 4 (4.0.3), and getting the above notification)

Notice: Trying to get property 'id' of non-object in
/home/photouri/stg-rds.reddustsnow.com.au/plugins/system/lscache/lscache.php on line 209

Referring to this:
`else {
            if($session->get('lastPostBack')==$this->menuItem->id){
                $this->pageCachable = false;
                $session->clear('lastPostBack');
            }`
Additionally, on the Home Dashboard, Notifications display "Unknown Joomla Version".

**Comment by iantrudell** [comment]
Same issue on Joomla 4 for me. My temporary fix:

In plugins/system/lscache/lscache.php, ~line 209, change this:
```php
if ($this->pageCachable && ($app->input->getMethod() != 'GET')) {
            $this->pageCachable = false;
            if ($this->menuItem && ($this->settings->get('purgePostBack', 0) == 1) ) {
                $purgeTags = "com_menus:" . $this->menuItem->id;
                $this->lscInstance->purgePublic($purgeTags);
                $session->set('lastPostBack', $this->menuItem->id);
                $this->log();
            }
        } else {
            if($session->get('lastPostBack')==$this->menuItem->id){
                $this->pageCachable = false;
                $session->clear('lastPostBack');
            }
        }
```

to this:
```php
if ($this->pageCachable && ($app->input->getMethod() != 'GET')) {
            $this->pageCachable = false;
            if ($this->menuItem && ($this->settings->get('purgePostBack', 0) == 1)) {
                if (isset($this->menuItem->id)) {
                    $purgeTags = "com_menus:" . $this->menuItem->id;
                    $this->lscInstance->purgePublic($purgeTags);
                    $session->set('lastPostBack', $this->menuItem->id);
                    $this->log();
                }
            }
        } else {
            if (isset($this->menuItem->id)) {
                if ($session->get('lastPostBack') == $this->menuItem->id) {
                    $this->pageCachable = false;
                    $session->clear('lastPostBack');
                }
            }
        }
```

**Comment by WuhuaChen** [comment]
Thanks for reporting this issue,  I just submit a fix in https://github.com/litespeedtech/lscache-joomla/commit/0b1cbb27deb2d359a1811e16437ebf1ade6af714 , also updated the joomla4 latest package : https://github.com/litespeedtech/lscache-joomla/blob/master/Joomla4/package/lscache-latest.zip
