### ISSUE TITLE
Integrate the cache cleaning with Joomla Cache Cleaner

### ISSUE THREAD

**Issue by gundestrup** [litespeedtech/lscache-joomla#5]
https://extensions.joomla.org/extension/cache-cleaner/
It can be done via
* url like calling a url: https://www.sitename.domain/litespeedcache.php?very long auth  code
* clean out a dir (have custom option)
* by contacting them to intergrate your product with theirs.

Their product, takes care of cache cleaning, when updating a site.

**Comment by jacksonlst** [comment]
thank for the feature request. Our developer has noted down and will include it in the future release.

**Comment by WuhuaChen** [comment]
In our new release, we already provide this feature via a url like 
https://www.sitename.domain/index.php?option=com_lscache&cleancache={auth code}
{auth code} can be configured via back end menu:
"components->LiteSpeedCache", click "options" button, then in "Advanced" tab, change the "Clean Cache Secure Words" field.

**Comment by gundestrup** [comment]
looks good, consider having a "copy" button to the right of the field, since the on mouse over is a bit hard to read....

**Comment by gundestrup** [comment]
looks good, closing the issue, consider addeing the info to readme file
