### ISSUE TITLE
Joomla 4 version using old mod_lscache instead of mod_lscache_purge in administrator

### ISSUE THREAD

**Issue by iantrudell** [litespeedtech/lscache-joomla#50]
On a fresh install with the Joomla 4 version of the plugin, it's still using administrator/mod_lscache instead of administrator/mod_lscache_purge in the status header of ACP.

**Comment by WuhuaChen** [comment]
Thanks for reporting,  fixed this problem in commit https://github.com/litespeedtech/lscache-joomla/commit/62a317c75e351a7bb193e8c084f94a76b2fc6d5c , now the 1.5.1 package for joomla4 will use mod_lscache_purge .
