### ISSUE TITLE
missing update of Joomla 3 package (from latest update to the libery)

### ISSUE THREAD

**Issue by gundestrup** [litespeedtech/lscache-joomla#52]

**Comment by M-Falken** [comment]
Hi
just download the whole archive
https://github.com/litespeedtech/lscache-joomla/archive/refs/heads/master.zip
you will find lscache-latest.zip in \lscache-joomla-master\Joomla3\package\

**Comment by gundestrup** [comment]
Dear Sir

Please note, the issue was created > 2 month ago, and was first resolved 4 days ago, with a release of a new version.
Not prior!

regards
Svend
