### ISSUE TITLE
Why no update improvement Joomla as with Wordpress?

### ISSUE THREAD

**Issue by ssnobben** [litespeedtech/lscache-joomla#53]
Q: Why is there no update improvement for Joomla as with Wordpress?

Its better to remove support for Joomla bcs Litespeed doesnt work for latest Joomla 4.2 so just remove everything related to Joomla so people doesnt waist their time!

**Comment by ch2856** [comment]
I am using lscache on joomla 4.2.3 and it works just fine, but I do wish we had some of the wordpress features like CSS/JavaScript/HTML Minification.

**Comment by M-Falken** [comment]
> I am using lscache on joomla 4.2.3 and it works just fine, but I do wish we had some of the wordpress features like CSS/JavaScript/HTML Minification.

? this is not the purpose of this plugin at all, you should look at JCH Optimize for example.
