### ISSUE TITLE
Virtuemart files still ok ?

### ISSUE THREAD

**Issue by M-Falken** [litespeedtech/lscache-joomla#55]
Hi,
As I see for example that those two lines below are in fact the only "patch" for this virtuemart file, I'm wonder if this 3.2.2 version is still ok, because I use VM 3.8.6 and VM is already on the 4.x serie.
Lots of diff between the 3.2.2 file and the 3.8.6 (and up to 3.8.9)
So same question for the /helpers/cart.php and /controllers/cart.php

https://github.com/litespeedtech/lscache-joomla/blob/b4220f1791ae735bc6887d47550b8492df5c7470/virtuemart/3.2.2/administrator/components/com_virtuemart/models/product.php#L2216
https://github.com/litespeedtech/lscache-joomla/blob/b4220f1791ae735bc6887d47550b8492df5c7470/virtuemart/3.2.2/administrator/components/com_virtuemart/models/product.php#L2217
Could you check please ?
Thanks to let us know about that

**Comment by WuhuaChen** [comment]
Hi,
if your virturemart version is higher than v3.2.2 then no need to patch the virtuemart to support litespeed cache plugin.  only lower versions need to be patched.

**Comment by M-Falken** [comment]
ok thanks
