### ISSUE TITLE
I don't see headers X-LiteSpeed-Cache "hit" "miss" in console

### ISSUE THREAD

**Issue by Darko-F** [litespeedtech/lscache-joomla#58]
Hi
Joomla! Version 4.2.8
PHP Version 8.1.13

I  install plugin and enable but I don't see headers X-LiteSpeed-Cache "hit" "miss" in console no matter what I do.

If I check https://check.lscache.io/ resoult is:

  LSCache is not supported

HTTP Header
HTTP/1.1 200 OK
Connection: Keep-Alive
Keep-Alive: timeout=5, max=100
x-frame-options: SAMEORIGIN
referrer-policy: strict-origin-when-cross-origin
cross-origin-opener-policy: same-origin
server-timing: 0Load;dur=4.175186;desc="Load", 1Initialise;dur=22.333860;desc="Initialise", 8Route;dur=0.829935;desc="Route", 26RenderComponentcomcontent;dur=5.076885;desc="RenderComponent com_content", 29Dispatch;dur=0.909090;desc="Dispatch", 88Render;dur=10.329962;desc="Render", Modules;dur=172.732830047607;desc="Modules", Access;dur=1.82104110717773;desc="Access"
content-type: text/html; charset=utf-8
expires: Wed, 17 Aug 2005 00:00:00 GMT
last-modified: Mon, 06 Mar 2023 15:30:53 GMT
cache-control: no-store, no-cache, must-revalidate, post-check=0, pre-check=0
pragma: no-cache
transfer-encoding: chunked
content-encoding: gzip
vary: Accept-Encoding,User-Agent
date: Mon, 06 Mar 2023 15:30:53 GMT
server: LiteSpeed
x-content-type-options: nosniff
alt-svc: h3=":443"; ma=2592000, h3-29=":443"; ma=2592000, h3-Q050=":443"; ma=2592000, h3-Q046=":443"; ma=2592000, h3-Q043=":443"; ma=2592000, quic=":443"; ma=2592000; v="43,46"

**Comment by fontanil** [comment]
Hi,

My host said we need to add in the .htaccess

CacheEnable public /

after

CacheEngine on

It works for me on the tested sites.
