### ISSUE TITLE
Wildcard or REGEX in the URL Exclusion List

### ISSUE THREAD

**Issue by jimhill10** [litespeedtech/lscache-joomla#6]
Is it possible to have a wildcard or REGEX in the URL exclusion list? Every one of our page URL's containing the word "thank" is excluded.  We would also like to exclude, if possible, any page already tagged with the URL "nocache."

**Comment by WuhuaChen** [comment]
OK, we'll implement this feature later and notify you.

**Comment by jimhill10** [comment]
Thanks so much.  I am testing the plugin right now and will report back any other issues.

**Comment by WuhuaChen** [comment]
In our new release, in the URL exclusion list, now we support REGEX, or a sub-string of target URL as well. thanks.

**Comment by jimhill10** [comment]
I test 1.01 and this works perfectly with a few of the simple REGEX's we have. In my case we just had two, one was the standard "nocache" which was carried over from the former htacess method.  Another was a unique URL term we always use in form submission thank you pages to prevent them from being cached.  Tested this is an it works as expected with no cache hit on those pages.
