### ISSUE TITLE
10 sec to save a joomla article

### ISSUE THREAD

**Issue by ch2856** [litespeedtech/lscache-joomla#60]
I used 1.5.1 but had an issue with a new component when saving an item I had an error "Attempt to assign property "id" on null"

I installed the latest version (https://github.com/litespeedtech/lscache-joomla/blob/master/Joomla4/package/lscache-latest.zip) which fix my issue but now saving a joomla article take over 10 sec. Not just saving an article, but every related thing to article such removing featured article option. 

J4.3.1
php 8.0.17

**Comment by WuhuaChen** [comment]
hi, you may disable auto recache feature if your site is complex or the vps performance is limited.
