### ISSUE TITLE
Is there something we can do to help you progress this project?

### ISSUE THREAD

**Issue by uglyeoin** [litespeedtech/lscache-joomla#61]
I see 33 issues and they seem to be stalled.  I'm on a Litespeed server so I would be keen to have a super fast website, but because of PHP errors I cannot use this software.  

Is there something we can do to help.  e.g. can the developers amongst us troubleshoot the issues and submit them and  get them accepted?  I see that there are 4 pull requests which are also not accepted.  

Do you need someone to help manage pull requests?  Or is there some other way we can help make this product work for Joomla?

**Comment by AndySDH** [comment]
@WuhuaChen

**Comment by ssnobben** [comment]
so whats the update here? @WuhuaChen  @litespeedtech @lslisa

**Comment by WuhuaChen** [comment]
hi, thanks for remind. I might ignored the GitHub issues,  since most issues was from our ticket system.
I will close solved issues and review those opened issues.

**Comment by uglyeoin** [comment]
Amazing, thank you @WuhuaChen looking forward to a more active GitHub repository so we can see some stability in the Joomla plugin.
